### ISSUE TITLE
Unable to install ufcg by conda

### ISSUE THREAD

**Issue by jun-yeong-heo** [steineggerlab/ufcg#23]
I'd tried to install ufcg in conda environment following the install guideline.
but I cannot able to install ufcg by `conda install -y -c bioconda ufcg`.

I've got the messages `Solving environment: unsuccessful initial attempt using frozen solve. Retrying with flexible solve.`
and `Solving environment: unsuccessful attempt using repodata from current_repodata.json, retrying with next repodata source.`,
and then `Collecting package metadata (repodata.json):` goes to infinite.

so I've tried to build it from source, although the installation succeeds, but when run it, I've repeatedly got an error `UFCG  |:  ERROR! Following dependency binary remains unsolved : fastBlockSearch`.

How can I bypass all these errors?
Any advice would be many appreciated.

**Comment by endixk** [comment]
Hello,

Seems like conda is struggling with resolving your environment due to the dependencies of our package.
I recommend you to use `libmamba-solver`, which should resolve environment solving issues:
```
conda update -n base conda
conda install -n base conda-libmamba-solver
conda config --set solver libmamba
```

If this doesn't work, please notice that the manual installation requires dependent programs to be installed manually as well.
Please visit [this page](https://ufcg.steineggerlab.com/ufcg/download) and follow the links to the requirements (`mmseqs`, `augustus`, `mafft` and `iqtree`) to complete the manual installation.

**Comment by jun-yeong-heo** [comment]
Hello,

Thanks for your kind advice.

But unfortunately I could not install the package on my conda environment using `libmamba-solver`.
I installed ufcg and the requirements manually and it works fine.

Thanks again.
